### ISSUE TITLE
五个建议：修改按钮；移除插件；修改图标；修改字符串；更新截图

### ISSUE THREAD

**Issue by mo-jinran** [MUKAPP/LiteLoaderQQNT-Homepage#1]
- 将 TG 群 修改为 Telegram 群
- 移除  轻量工具箱 插件
- 将 Topbar 左侧图标修改为 圆形
- 将所有的 LiteLoader 改为 LiteLoaderQQNT 
- 配置界面 截图更新为 新版 0.2.0 配置界面

**Comment by MUKAPP** [comment]
起床.jpg

**Comment by MUKAPP** [comment]
![image](https://github.com/MUKAPP/LiteLoaderQQNT-Homepage/assets/41848070/0d2b0f28-a018-4d8a-af06-85481f154971)
移除了轻量工具箱插件之后还要加其他的吗

**Comment by MUKAPP** [comment]
ok了 https://github.com/MUKAPP/LiteLoaderQQNT-Homepage/commit/d427f6585e93a69bf05d972d3be6b3f2ead2371b

**Comment by mo-jinran** [comment]
> ![image](https://user-images.githubusercontent.com/41848070/260314733-0d2b0f28-a018-4d8a-af06-85481f154971.png) 移除了轻量工具箱插件之后还要加其他的吗

加吧，少一个怪难看的

**Comment by MUKAPP** [comment]
要加个什么
